version: '3.4'

services:
  poliklinika.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "2345:80"

  bogcha.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4545:80"
